### ISSUE TITLE
arduino 如何通过mqtt接受树莓派的控制指令

### ISSUE THREAD

**Issue by shun-wei** [hpecl-sspku/2018#16]
由于arduino内存只有2k,增加控制命令后，内存不足，现在可以向树莓派publish传感器数据，无法subscribe树莓派的命令，空调的控制为长为236的数组。

**Comment by RunningGump** [comment]
我们未能解决这个问题，但是我们改变了策略，将二级管接在了树莓派上，可以通过树莓派发射命令控制电器
