### ISSUE TITLE
arduino 与树莓派MQTT通信

### ISSUE THREAD

**Issue by shun-wei** [hpecl-sspku/2018#2]
目前arduino与树莓派MQTT通信已经解决。

**Comment by HWuan** [comment]
通过遥控器发生的红外码已经接受破解，以开关机为例，不通模式，不同温度，nec码都不同，需要将nec码转为raw码，已经转化完成，尚不清楚每一位的具体含义，通过红外管发生raw码，空调尚无反应。
![IRrecvTest](https://user-images.githubusercontent.com/43475107/55949647-ab8c1180-5c85-11e9-9171-e66510f7b516.png)
